language: julia
os:
  - linux
julia:
  - 1.0
notifications:
  email: false
git:
  depth: 99999999
cache:
  timeout: 1000
  directories:
    - downloads
env:
  global:
    - BINARYBUILDER_DOWNLOADS_CACHE=downloads
    - BINARYBUILDER_AUTOMATIC_APPLE=true
sudo: required
# Before anything else, get the latest versions of things
before_script:
  - julia -e 'using Pkg; pkg"add BinaryProvider"; pkg"add BinaryBuilder#master"; Pkg.build()'
script:
  - julia build_tarballs.jl
deploy:
  provider: releases
  api_key:
    secure: "rw9Mo9lKDWVHaGg+cnJqp/NWRsEg16nsm0/95P0DFwutzRHxwYiBMXoPThbVAE585ad99JbatiWr9yT+xzTgqNTMlJDQYV5ozlfqkBAhboA4qNlH27tvRNcjjxof3I76+IICTt5boXGZdvKrXwvPdd38C6WB/bgnGMpveFykM7CcQxAYN2fQuVoFnFzeVnJX6YdfHPw1pXG6uRECtlF+gDGCT318XfMatLxuaWQz5j1RdpfPYpCFj07PCKNjLhSZhqGzSVkQyNhCeqfRSGBUKpQhuH1IAVAfq4xGQh781W3bPpo6z9CM2nJ3R4AYz6SqCvsBALbo3TjnQT8MBr42pLYz36xtXHKHYRh9FD/sUGtTaT9tw2NS/ZbcbdLHRdhMix0eQyQOh+Qh4uN8P2yAb2+RiPRPnDONJnrcS6QpoV3Kjrh2+ccG+xEcZCE0sBE9DGAaAm224sTJR8bLQP5XRC9wW+4pX29Z7eDAgFlxWGCFcjfknGpziHXKRsldE7NHmnIW0kgBGBfoKIkJgeaOkl37uA6uykIz2qZWZqK3i8zz5IuKtuJz7WHoHJEYxmMYvQUbAhKVPXlnMp4hC4S5vEGac9UQNLLBvES7It/Dxa3eolSOtfD8OOMrj/kymnO5xPwVTZchxq7rqVlZfL7yIBxQR3phnvRiYCUYefIrHmk="
  file_glob: true
  file: $TRAVIS_BUILD_DIR/products/*.tar.gz
  skip_cleanup: true
  on:
    repo: invenia/LibPQBuilder
    tags: true
